language: rust

rust: stable

os: osx

osx_image: xcode10.3

addons:
  homebrew:
    packages:
    - cmake
    casks:
    - vulkan-sdk
    taps:
    - apenngrace/vulkan
    
script: cargo build --release && cd target/release/neovide && ls

